---
title: "prog-concepts"
output: html_document
---

# Functions

## Setup
```{r}

library(pbda)
library(tidyverse)
library(cowplot)

```

## A simple example
```{r}

a <- rnorm(n = 10)
a

# Rescale this so all values are between 0 and 1
(a - min(a)) / (max(a) - min(a))

rng <- range(a)
(a - rng[1]) / (rng[2] - rng[1])


b <- rnorm(n = 10)
c <- rnorm(n = 10)


rng <- range(b)
new_b <- (b - rng[1]) / (rng[2] - rng[1])

rng <- range(c)
new_c <- (c - rng[1]) / (rng[2] - rng[1])

```

## Function structure
```{r}

# Good names
#rescale_vec

# Bad names 
#my_fav_fun
#my_function_to_rescale_a_vector


rng <- range(b)
new_b <- (b - rng[1]) / (rng[2] - rng[1])


rescale_vec <- function(x) {
  
  rng <- range(x)
  (x - rng[1]) / (rng[2] - rng[1]) + 1

} 

rescale_vec(a)
rescale_vec(b)
rescale_vec(c)

```

```{r}

# function 1

calc_prop <- function(x) {
  
  x / sum(x)
  
}

# function 2
calc_sum_div <- function(x, y, z) {
  
  (x + y) / z
  
}


# function 3
calc_sd <- function(x) {
  
  m <- mean(x)
  l <- length(x) -1
  v <- sum((x - m)^2) / l
  sqrt(v)
  
}

```

## Brauer example
```{r}

plot_expr <- function(input, sys_name = "YDL104C") {
  
  gg_data <- input %>%
    filter(systematic_name == sys_name)
  
  plot_title <- gg_data$name[1]
  plot_sub <- gg_data$MF[1]
  
  gg_data %>%
    ggplot(aes(rate, expression, color = nutrient)) + 
    geom_point(size = 4) +
    facet_wrap(~ nutrient) +
    labs(title = plot_title, subtitle = plot_sub) +
    theme(legend.position = "none") +
    theme_cowplot()
  
}

plot_expr(
  input = brauer_gene_exp,
  sys_name = "YDL104C"
)

brauer_gene_exp %>%
  plot_expr()

```

## `if` statements
```{r}

x <- c("dog", "cat", "fish")

if ("car" %in% x) {
  
  print("in x")
  
} else {
  print("not in x")
}

```

```{r}

plot_expr <- function(input, sys_name = "YDL104C") {
  
  gg_data <- input %>%
    filter(systematic_name == sys_name)
  
  plot_title <- gg_data$name[1]
  
  if (plot_title == "") {
    plot_title <- gg_data$systematic_name[1]
  }

  plot_sub <- gg_data$MF[1]
  
  gg_data %>%
    ggplot(aes(rate, expression, color = nutrient)) + 
    geom_point(size = 4) +
    facet_wrap(~ nutrient) +
    labs(title = plot_title, subtitle = plot_sub) +
    theme(legend.position = "none") +
    theme_cowplot()
  
}

plot_expr(
  input = brauer_gene_exp,
  sys_name = "YNL095C"
)

```

```{r}

length(x)

if ("car" %in% x || length(x) == 3) {
  print("something")
  
} else if ("hook" %in% x) {
  print("something else")
  
} else {
  print("another thing")
}

```

## Checking types
```{r}

plot_expr <- function(input, sys_name = "YDL104C") {
  
  if (!is.character(sys_name)) {
    stop("sys_name is not a character string!!!!!")
  }
  
  if (!sys_name %in% input$systematic_name) {
    stop("sys_name not found in data!!!!!")
  }
  
  gg_data <- input %>%
    filter(systematic_name == sys_name)
  
  plot_title <- gg_data$name[1]
  
  if (plot_title == "") {
    plot_title <- gg_data$systematic_name[1]
  }

  plot_sub <- gg_data$MF[1]
  
  gg_data %>%
    ggplot(aes(rate, expression, color = nutrient)) + 
    geom_point(size = 4) +
    facet_wrap(~ nutrient) +
    labs(title = plot_title, subtitle = plot_sub) +
    theme(legend.position = "none") +
    theme_cowplot()
  
}

plot_expr(
  input = brauer_gene_exp,
  sys_name = "YNL095Cfasdfsadfas"
)

```

## Passing arguments with the ellipsis
```{r}

a[1] <- NA

rescale_vec <- function(x, ...) {
  
  rng <- range(x, ...)
  
  (x - rng[1]) / (rng[2] - rng[1])

}

rescale_vec(x = a, na.rm = T)

```

*Modify our plotting function so the user can change the point size, shape, and alpha*
```{r}

plot_expr <- function(input, sys_name = "YDL104C", ...) {
  
  gg_data <- input %>%
    filter(systematic_name == sys_name)
  
  plot_title <- gg_data$name[1]
  plot_sub <- gg_data$MF[1]
  
  gg_data %>%
    ggplot(aes(rate, expression, color = nutrient)) + 

    geom_point() +
  
    facet_wrap(~ nutrient) +
    labs(title = plot_title, subtitle = plot_sub) +
    theme(legend.position = "none") +
    theme_cowplot()
}

plot_expr(
  input = brauer_gene_exp, 
  sys_name = "YNL049C",
  size = 8,
  shape = 2,
  alpha = 0.6
)
```








